[package]
name = "ascii-pay-authentication-proxy"
version = "0.1.0"
authors = ["Lars Westermann <lars-westermann@live.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.0"
actix-web = "2.0"
tokio = "0.2"
evdev-rs = "0.3"
dotenv = "0.15"
futures = "0.3"
url = "1.7"
env_logger = "0.6"
ctrlc = { version = "3.0", features = ["termination"] }
pcsc = "2.3"
